### ISSUE TITLE
Multi-select for machine filter

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#247] opened 2019-07-09 04:53 UTC
One thing I've run into is wanting to search for a machine, regardless if it's a premium, pro, LE, etc. This came up last weekend when my wife played Batman 66 at Salt Lake's Gaming Con. She asked me if there was a location nearby with the table and she didn't really care which version. I had to do three different searches, one for each version, to see if there was a location nearby with one. At first, I thought it'd be a good idea to group all versions of the same machine together, but I think it'd be better if you could just do a multi-select when filtering machines. That way you can group all versions of the same machine together and even add other machines if interested. Not sure how the API calls on the backend would be, but looks like on the UI side you could use something like https://www.npmjs.com/package/react-native-multiple-select.

The past few weeks have been crazy but I may have some time coming up to take a look to see if it'd be feasible at least.

**Comment by metroshica** [comment] 2019-07-09 04:57
Thinking a bit more about this, I'm assuming each selection would probably be a separate API call (unless the API currently has the ability to search for multiple machines in one query). It'd probably be worth putting a cap on the number of machines you can select at once. That way you don't have some genius selecting 500 machines and then simultaneously sending 500 API calls every time they pan around with the filter applied.

**Comment by RyanTG** [comment] 2019-07-09 05:39
Actually, we do group all versions of the same machine together. That's how we've done it for years, because we found that most people don't care which version they're looking up and it's a hassle to do multiple searches. We set up a category called "machine groups", and we add all versions of a machine to the same group. Searches basically work like: IF part of a machine group, then display all machines within that group, ELSE just show that one machine.

It's even on the FAQ! https://github.com/bpoore/pbm-react/blob/master/app/screens/FAQ.js#L45

I just doublechecked this on the app (zoomed in on a place with Iron Maiden, and applied a filter for three different versions of the machine), and this is working as intended.

Are you super sure that you _had_ to conduct three searches to see all versions of a machine? If so, perhaps this is an Android-only issue... but that would be bizarre.

**Comment by bpoore** [comment] 2019-07-09 05:45
It’s possibly not as obvious as it should be, but currently searching for any one version of a machine returns all results of all types of that machine (the api is taking care of this for us). I agree it would be cool to be able to filter by multiple machines or to eventually choose a specific version of a specific machine but that will require additional changes to the api.

For the app, we have a multi-select version of the machine selection component which is being used for the ‘suggest location’ screen- so ideally if we could allow an array of machines for the filter request, we could be easily ready to go. Currently, we can’t filter by more than one machine as we are doing all filtering for a given map extent via a single request to the api. I strongly believe it would be easier to make an issue / PR against the api repo to allow for multiple machine selection than trying to piece together requests from the app.

**Comment by bpoore** [comment] 2019-07-09 05:47
Oops- quasi  simultaneous reply! I will keep mine up as well as it is slightly different as Ryan’s.

**Comment by metroshica** [comment] 2019-07-09 12:42
Well, I "had" to conduct three searches as no one in my area has the table. All searches came up empty. I searched three times as I assumed it was per type of machine. Now that you say that, I remember it being in the FAQ. Maybe it should be a bit more clear in the filter section so idiots like me don't miss it? Possibly by not listing each individual machine, just top level and then when you click on the location it shows you the specific type. Or just leave it as is.

Scrapping that terrible example, I still think it'd be nice to select multiple machines though. Since I live in a table-sparse area, I have wanted to play just one of five or so machines. It'd be nice to load up those five in a selection and then see which locations have them.

**Comment by bpoore** [comment] 2019-07-09 17:56
Ahh, that makes a lot of sense, @metroshica and a good reason to make the selection more clear. It looks like from the API (https://pinballmap.com/api/v1/machines.json) we are getting a field back of `machine_group_id`. It would be possible to do something along the lines of rather than displaying the _specific_ machine type here:

<img width="421" alt="Screen Shot 2019-07-09 at 10 36 58 AM" src="https://user-images.githubusercontent.com/7720282/60910406-8d5a9100-a235-11e9-8369-c4651fa03665.png">

we could indicate rather it is selecting all versions of this machine. To do much more than that at this time, we would need to coordinate to make some changes to the API to allow for different behavior. 

The different text would go here if you are interested in working on this: https://github.com/bpoore/pbm-react/blob/master/app/screens/FilterMap.js#L99

The machine object coming in from the Redux state has all the info that's available in the API including if it has a group id, so the logic here wouldn't be too complicated if we wanted to make the machine selected more obviously a group selection: 
``` 
{
   "created_at": "2012-07-18T18:52:50.714-07:00",
   "id": 1329,
   "ipdb_id": 5777,
   "ipdb_link": "http://www.ipdb.org/machine.cgi?id=5777",
   "is_active": false,
   "machine_group_id": 1,
   "manufacturer": "Stern",
   "name": "AC/DC (LE)",
   "nameManYear": "AC/DC (LE) (Stern, 2012)",
   "opdb_id": "G43W4-MrRpw-A1B7O",
  "updated_at": "2018-07-16T09:00:55.301-07:00",
   "year": 2012,
}
```

I have some time this evening as well and can get this change in myself if there are other things you'd like to tackle. I think we're looking to get a new build out in the coming few days. 

Thanks for the feedback. I think it will be nice to update the field on the filter screen to make it obvious what is going on.

**Comment by bpoore** [comment] 2019-07-10 17:16
What do you both think of this? b6b751fac1d1f78012d6384e56d05f5e46d4971c

@RyanTG @metroshica

**Comment by metroshica** [comment] 2019-07-10 17:58
I like it, the "All Versions" in the title makes it really clear once it's selected. This is definitely nitpicky, but it might be good to put logic in the header above to change "Only show locations with this machine:" to be "Only show locations with **these machines**:  since you're now referring to a group instead of a specific machine.

The only other thing to consider (which would probably be a pain without changing the API) is having this grouping in the machine list dropdown. That way the user knows that it's filtering for all versions of the machine when they actually select it. Then again, then you might want to have some sort of option to override the grouping and only filter select machines if someone is specifically looking for an LE or Premium, but then all the edge cases become fun...

**Comment by RyanTG** [comment] 2019-07-10 18:43
I'll check it out later today. 

Just a note: we get about one person a year complaining about not being able to search for _just_ that particular machine (and sometimes it's the same guy sending us a yearly reminder that he wants this behavior JUST so he can more easily leave comments that say, "The one and only Cool Machine (LE) in this part of the state!"). So, it would be a neat feature, but based on interest/need it's not a priority.

Also, in addition to changing the API for displaying the machine group in the dropdown, I'd need each machine group name. Not a big deal - but just a tedious step. Right now the groups use acronyms instead of full names.

**Comment by bpoore** [comment] 2019-07-10 19:04
Word. This was just a quick and dirty way to represent how the search for filtering is actually working at this time. Agree we could improve it over time if people really want it to have more options, but this was hopefully just going to help make it clear how the machine search for filtering by machine was working under the hood.

**Comment by RyanTG** [comment] 2019-07-11 06:03
Yeah, this seems great. Thanks!

**Comment by RyanTG** [comment] 2019-07-14 22:24
@metroshica Are you planning on working on this? Otherwise, I'll close this issue because I think it's adequately addressed.

**Comment by metroshica** [comment] 2019-07-15 03:13
Just close it. Too slammed right now and I'm about to head out of the country for a couple of weeks. I'll tool around with it when I have some time but I wouldn't keep it open on my account.

**Closed** 2019-07-15 22:39 UTC
Labels: pending review
