### ISSUE TITLE
Current location not updating after initial app load

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#220] opened 2019-06-10 01:22 UTC
The current location button only updates its location on app load. To replicate, open the app and then move a measurable distance from your initial location (tested this by hopping in my car and driving a couple of blocks over). Press the current location button and it will go back to where you were when you opened the app, not where you are currently located. Easy to tell as the map doesn't center on your blue dot, which is still visible if you're in the general vicinity of the initial load location.

**Comment by RyanTG** [comment] 2019-06-10 03:03
Duplicate of https://github.com/bpoore/pbm-react/issues/215

But we’ll-explained.

**Closed by RyanTG** 2019-06-10 03:03 UTC
